# Generated by Django 2.1.4 on 2019-08-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190825_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.TextField(blank=True, default='SOSA Member', max_length=200),
        ),
    ]
