# Generated by Django 2.1.4 on 2019-08-25 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190825_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.TextField(blank=True, default='SOSA Member', max_length=500),
        ),
    ]
