# Generated by Django 2.1.4 on 2019-01-30 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_events'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
