# Generated by Django 2.1.4 on 2019-08-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190728_1917'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery',
        ),
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.FileField(blank=True, default='lotus.jpeg', upload_to=''),
        ),
    ]
