# Generated by Django 2.1.4 on 2019-08-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20190826_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, default='lotus.jpeg', upload_to=''),
        ),
    ]
