# Generated by Django 2.1.4 on 2019-10-28 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20191023_1923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('event_date',)},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('date_posted',)},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='posted_by',
        ),
    ]
